services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile
    # command: uv sync --dev
    env_file:
      - .env
    volumes:
      # Either keep the config on your host...
      - $HOME/.config/goose:/home/developer/.config/goose
      # ...or use a persistent volume within Docker.
      # - config:/home/developer/.config
      # FIXME: You'll want to customize this to match the directories you want
      #     to share.
      # - $HOME/Code/SFU:/app/code
      - $HOME/Code:/app/code:cached
# volumes:
#   config:
